matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - os: linux
      language: node_js
      node_js: "10"
      addons:
        apt:
          packages:
          - libudev-dev
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

if: tag IS present

script:
  - echo 'no action on regular hook'

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then rm -fr ~/private_keys && mkdir ~/private_keys                                    ; fi 
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then echo $AUTH_PRIVATE_KEY | base64 -D > ~/private_keys/AuthKey_${APPLE_API_KEY}.p8  ; fi 

deploy:
  - provider: script
    script: npm run build
    skip_cleanup: true
    on:
      tags: true
