matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - os: linux
      language: node_js
      node_js: "10"
      addons:
        apt:
          packages:
          - libudev-dev
    - os: windows
      language: node_js
      node_js: "10"

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - npm install node-gyp@latest -g

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm_config_node_gyp="C:\ProgramData\nvs\node\10.19.0\x64\node_modules\npm\node_modules\node-gyp"    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then echo $npm_config_node_gyp                                                                           ; fi
  - npm ls node-gyp -g
  - npm run build

deploy:
  - provider: script
    script: npm run build
    skip_cleanup: true
    on:
      tags: true
